"use client";
import { Navbar } from "@/components";
import Head from "next/head";
import "../globals.css";
import "../../public/fontello/css/blockquote.css"
import { Kumbh_Sans } from "next/font/google";

const kumbhSans = Kumbh_Sans({
  style: "normal",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={kumbhSans.className}>
        <Navbar />
        <div className="my-4">{children}</div>
      </body>
    </html>
  );
}
